name: Build S1S3 ROMs

on:
  push:
    branches: [flamedriver, Clone-Driver-v2]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set branch variable
        shell: powershell
        run: |
          $branch = $env:GITHUB_REF -replace 'refs/heads/', ''
          echo "BRANCH_NAME=$branch" >> $env:GITHUB_ENV

      - name: Run build.bat
        run: cmd /c build.bat

      - name: Run build_debug.bat
        run: cmd /c build_debug.bat

      - name: Upload ROMs
        uses: actions/upload-artifact@v4
        with:
          name: ROMs-${{ env.BRANCH_NAME }}
          path: |
            S1S3.gen
            S1S3.debug.gen
