name: Build S1S3 ROMs

on:
  push:
    branches:
      - flamedriver
      - Clone-Driver-v2

    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '_CD/**'
      - 'Engine/_examples/**'
      - 'Projects/**'
      - 'Utilities/**'

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set branch variable
        shell: pwsh
        run: |
          $branch = $env:GITHUB_REF -replace 'refs/heads/', ''
          echo "BRANCH_NAME=$branch" >> $env:GITHUB_ENV

      - name: Run build.bat
        shell: cmd
        run: |
          cd /d %GITHUB_WORKSPACE%
          build.bat

      - name: Run build_debug.bat
        shell: cmd
        run: |
          cd /d %GITHUB_WORKSPACE%
          build_debug.bat

      - name: Upload ROMs
        uses: actions/upload-artifact@v4
        with:
          name: ROMs-${{ env.BRANCH_NAME }}
          path: |
            S1S3.gen
            S1S3.debug.gen
